### PR TITLE
Fixes to glance provider to handle exceptional conditions.

### PR DESCRIPTION
**Pull request by Jorge-Rodriguez**
Don't raise FnF if there is an image locally.
Don't download non-active images.
Perform atomic downloads.

### CODE REVIEW

**Comment by noxdafox** [comment]
Is this logic covered by tests?

I would add on the Glance plugin documentation the fact that old images don't get removed automatically but it's the User's responsibility.

We could also add the deletion ourselves. An optional configuration flag in the plugin's config where, if set, it deletes old images if older than X (X is the config value in seconds/hours/days/centuries).

**Comment by Jorge-Rodriguez** [comment]
@noxdafox I wouldn't add local deletion capabilities at all. These are image providers, not image managers. Each instance of the provider should take care of placing a requested image where the client expects it and nothing more. Cleanup is the client's responsibility, for this and any other providers as the provider cannot know how or by whom the image is being used or when.

I'll update the providers' documentation in general to explicitly note that providers DO NOT clean after themselves in any case.

**Comment by noxdafox** [comment]
Conflicts on the branch.

**Comment by Jorge-Rodriguez** [comment]
@dangonzo Could you be more specific?

**Pull request merged**
